path: '/content/gdrive/Mi unidad/DetectorTornillos/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

names:
  0: squirrel

